[theme]
primaryColor = "#142A4F"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[logger]
level = "error"

[client]
toolbarMode = "minimal"
showErrorDetails = true